name = "coffee"
version = "1.0.0"

description = "â˜• Coffee - codegen in gleam made easy"
licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "coffee" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
